import = [
  "~/.config/alacritty/fonts.toml",
  "~/.config/alacritty/catppuccin-mocha.toml"
]
live_config_reload = true

[window]
opacity = 0.95

[window.padding]
x = 18
y = 16

[cursor.style]
shape = "Block"
blinking = "On"
