# ~/.config/starship.toml

add_newline = true                     # Inserts a blank line between shell prompts
command_timeout = 1000                 # Change command timeout from 500 to 1000 ms
format = """$username $env_var $all""" # Add custom formatting before other stuff

# Add color palette
palette = "thanos"

[palettes.thanos]
  space = "#00A1E4"
  reality = "#FF206E"
  power = "#9D65FF"
  soul = "#FABC2A"
  vision = "#DDA2F6"
  time = "##58EBD7"
  supernova = "#F8F8F0"
  mind = "#FFE900"


# Drop ugly default prompt characters
[character]
  success_symbol = '[](bold red)[](bold yellow)[](bold green)'
  error_symbol = '[](bold red)'

# Shows current username
[username]
  format = '[$user]($style)'
  style_user = "space bold"
  style_root = "soul bold"
  disabled = false
  show_always = true

# ---
# Shows an icon depending on what device it is running on
[env_var.STARSHIP_DEVICE]
  format = 'on [$env_value ](bold soul)'
  variable = "STARSHIP_DEVICE"
  disabled = false

# Shows the hostname
[hostname]
  ssh_only = false
  format = "[$hostname](bold soul) "
  disabled = false

# Shows an icon depending on what distro it is running on
[env_var.STARSHIP_DISTRO]
  format = '[ 󱕆  $env_value ](bold soul)'
  variable = "STARSHIP_DISTRO"
  disabled = false

# Shows current directory
[directory]
  truncation_length = 2
  home_symbol = "  ~"
  read_only_style = "197"
  read_only = "  "
  format = "at [$path]($style)[$read_only]($read_only_style) "

# Shows current git branch
[git_branch]
  symbol = " "
  format = "via [$symbol$branch]($style)"
  # truncation_length = 4
  truncation_symbol = "…/"
  style = "bold green"

# Shows current git status
[git_status]
  format = '[$all_status$ahead_behind]($style) '
  style = "bold green"
  conflicted = "  "
  untracked = "  "
  ahead = " ⇡${count}"
  diverged = " ⇕⇡${ahead_count}⇣${behind_count}"
  behind = " ⇣${count}"
  stashed = " "
  modified = "  "
  staged = '[ 󱅃 \($count\)](green)'
  renamed = "  "
  deleted = "  "


# Shows kubernetes context and namespace
[kubernetes]
  format = 'via [󰠳 $context\($namespace\)](bold vision) '
  disabled = false

# Shows localip for ssh-connections
[localip]
  ssh_only = true
  format = '[\( $localipv4\)](bold space) '
  disabled = false
